/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return backend health and connection status.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Words
         * @description Fetch sample Japanese vocabulary cards from Supabase or fallback list.
         */
        get: operations["get_test_words_api_test_words_get"];
        put?: never;
        /**
         * Create Test Word
         * @description Create a new word card in Supabase or memory.
         */
        post: operations["create_test_word_api_test_words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckStatus */
        HealthCheckStatus: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * App
             * @example Gesenu API
             */
            app: string;
            /**
             * Version
             * @example 0.1.0
             */
            version: string;
            /**
             * Supabase Connected
             * @example true
             */
            supabase_connected: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WordCard */
        WordCard: {
            /**
             * Id
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string | null;
            /**
             * Lemma
             * @example 解せる
             */
            lemma: string;
            /**
             * Reading
             * @example かいせる
             */
            reading: string;
            /**
             * Meaning
             * @example to make sense of; comprehend
             */
            meaning: string;
            /**
             * Jlpt Level
             * @example N1
             */
            jlpt_level?: string | null;
            /**
             * Context Sentence
             * @example 複雑な文法構造を分解すれば、どんな難文でも解せるようになる。
             */
            context_sentence: string;
            /**
             * Status
             * @default New
             * @example Learning
             */
            status: string;
        };
        /** WordCardResponse */
        WordCardResponse: {
            /** Words */
            words: components["schemas"]["WordCard"][];
            /**
             * Source
             * @example supabase
             */
            source: string;
            /**
             * Message
             * @example Fetched successfully
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckStatus"];
                };
            };
        };
    };
    get_test_words_api_test_words_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCardResponse"];
                };
            };
        };
    };
    create_test_word_api_test_words_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordCard"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
