/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return backend health and Supabase connection status.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Japanese Sentence
         * @description Parse a raw Japanese sentence using SudachiPy into tokenized words.
         */
        post: operations["parse_japanese_sentence_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dict/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dictionary Lookup
         * @description Look up dictionary entry, readings, meanings, and JLPT level via Jisho API.
         */
        get: operations["dictionary_lookup_api_dict_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Words
         * @description Fetch Japanese vocabulary cards from Supabase PostgreSQL.
         *     Only falls back when server fails.
         */
        get: operations["get_words_api_words_get"];
        put?: never;
        /**
         * Create Word
         * @description Create and save a new word card in Supabase PostgreSQL.
         */
        post: operations["create_word_api_words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Words
         * @description Fetch Japanese vocabulary cards from Supabase PostgreSQL.
         *     Only falls back when server fails.
         */
        get: operations["get_words_api_test_words_get"];
        put?: never;
        /**
         * Create Word
         * @description Create and save a new word card in Supabase PostgreSQL.
         */
        post: operations["create_word_api_test_words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DictLookupResponse */
        DictLookupResponse: {
            /**
             * Lemma
             * @example 解せる
             */
            lemma: string;
            /**
             * Reading
             * @example かいせる
             */
            reading: string;
            /**
             * Meaning
             * @example to understand; to comprehend
             */
            meaning: string;
            /**
             * Jlpt Level
             * @example N1
             */
            jlpt_level?: string | null;
            /**
             * Found
             * @example true
             */
            found: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckStatus */
        HealthCheckStatus: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * App
             * @example Gesenu API
             */
            app: string;
            /**
             * Version
             * @example 0.2.0
             */
            version: string;
            /**
             * Supabase Connected
             * @example true
             */
            supabase_connected: boolean;
        };
        /** ParseSentenceRequest */
        ParseSentenceRequest: {
            /**
             * Sentence
             * @example 複雑な文法構造を分解すれば、どんな難文でも解せるようになる。
             */
            sentence: string;
        };
        /** ParseSentenceResponse */
        ParseSentenceResponse: {
            /** Sentence */
            sentence: string;
            /** Tokens */
            tokens: components["schemas"]["TokenItem"][];
            /** Candidate Count */
            candidate_count: number;
        };
        /** TokenItem */
        TokenItem: {
            /**
             * Surface
             * @example 走った
             */
            surface: string;
            /**
             * Lemma
             * @example 走る
             */
            lemma: string;
            /**
             * Reading
             * @example はしる
             */
            reading: string;
            /**
             * Pos
             * @example 動詞
             */
            pos: string;
            /**
             * Pos Detail
             * @example 動詞-一般
             */
            pos_detail: string;
            /**
             * Span Start
             * @example 0
             */
            span_start?: number | null;
            /**
             * Span End
             * @example 3
             */
            span_end?: number | null;
            /**
             * Is Selectable
             * @example true
             */
            is_selectable: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WordCard */
        WordCard: {
            /**
             * Id
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string | null;
            /**
             * Lemma
             * @example 解せる
             */
            lemma: string;
            /**
             * Surface Form
             * @example 解せる
             */
            surface_form?: string | null;
            /**
             * Span Start
             * @example 17
             */
            span_start?: number | null;
            /**
             * Span End
             * @example 20
             */
            span_end?: number | null;
            /**
             * Sentence Id
             * @example sent-1
             */
            sentence_id?: string | null;
            /**
             * Reading
             * @example かいせる
             */
            reading: string;
            /**
             * Meaning
             * @example to make sense of; comprehend
             */
            meaning: string;
            /**
             * Jlpt Level
             * @example N1
             */
            jlpt_level?: string | null;
            /**
             * Context Sentence
             * @example 複雑な文法構造を分解すれば、どんな難文でも解せるようになる。
             */
            context_sentence: string;
            /**
             * Status
             * @default New
             * @example Learning
             */
            status: string;
        };
        /** WordCardResponse */
        WordCardResponse: {
            /** Words */
            words: components["schemas"]["WordCard"][];
            /**
             * Source
             * @example supabase
             */
            source: string;
            /**
             * Message
             * @example Fetched successfully
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckStatus"];
                };
            };
        };
    };
    parse_japanese_sentence_api_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseSentenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseSentenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dictionary_lookup_api_dict_lookup_get: {
        parameters: {
            query: {
                /** @description Target lemma or Japanese word */
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_words_api_words_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCardResponse"];
                };
            };
        };
    };
    create_word_api_words_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordCard"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_words_api_test_words_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCardResponse"];
                };
            };
        };
    };
    create_word_api_test_words_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordCard"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
