import type { DeckItem, WordCard, TokenItem } from '../types/app';

export const API_BASE = import.meta.env.VITE_API_BASE || '';

export const NEXT_STATUS: Record<string, string> = {
  New: 'Learning',
  Learning: 'Known',
  Known: 'Mastered',
  Mastered: 'New',
};

export const SAMPLE_SENTENCES = [
  'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
  '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。',
  '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
];

export const DEMO_PARSE_MAP: Record<string, TokenItem[]> = {
  'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。': [
    { surface: 'コンビニ', lemma: 'コンビニ', reading: 'こんびに', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'で', lemma: 'で', reading: 'で', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '買い物', lemma: '買い物', reading: 'かいもの', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'し', lemma: 'する', reading: 'し', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'き', lemma: 'くる', reading: 'き', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: '後', lemma: '後', reading: 'あと', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: '、', lemma: '、', reading: '、', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
    { surface: 'くたびれ', lemma: '草臥れる', reading: 'くたびれる', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: '様子', lemma: '様子', reading: 'ようす', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'で', lemma: 'で', reading: 'で', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '街', lemma: '街', reading: 'まち', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'うろうろ', lemma: 'うろうろ', reading: 'うろうろ', pos: '副詞', pos_detail: '副詞', is_selectable: true },
    { surface: 'し', lemma: 'する', reading: 'し', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'いる', lemma: 'いる', reading: 'いる', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'は', lemma: 'は', reading: 'は', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '、', lemma: '、', reading: '、', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
    { surface: '料理', lemma: '料理', reading: 'りょうり', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '作る', lemma: '作る', reading: 'つくる', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'が', lemma: 'が', reading: 'が', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '面倒くさかっ', lemma: '面倒臭い', reading: 'めんどうくさい', pos: '形容詞', pos_detail: '形容詞', is_selectable: true },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: 'から', lemma: 'から', reading: 'から', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'だ', lemma: 'だ', reading: 'だ', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: '。', lemma: '。', reading: '。', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
  ],
  '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。': [
    { surface: '昔', lemma: '昔', reading: 'むかし', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '思い出', lemma: '思い出', reading: 'おもいで', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '振り返っ', lemma: '振り返る', reading: 'ふりかえる', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '泣き', lemma: '泣く', reading: 'なく', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'そう', lemma: 'そう', reading: 'そう', pos: '形状詞', pos_detail: '形状詞', is_selectable: false },
    { surface: 'に', lemma: 'に', reading: 'に', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: 'なっ', lemma: 'なる', reading: 'なる', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: 'が', lemma: 'が', reading: 'が', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '、', lemma: '、', reading: '、', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
    { surface: '切なかっ', lemma: '切ない', reading: 'せつない', pos: '形容詞', pos_detail: '形容詞', is_selectable: true },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: '気持ち', lemma: '気持ち', reading: 'きもち', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '反面', lemma: '反面', reading: 'はんめん', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: '、', lemma: '、', reading: '、', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
    { surface: '心', lemma: '心', reading: 'こころ', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'は', lemma: 'は', reading: 'は', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'ドキドキ', lemma: 'ドキドキ', reading: 'どきどき', pos: '副詞', pos_detail: '副詞', is_selectable: true },
    { surface: 'し', lemma: 'する', reading: 'し', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'いる', lemma: 'いる', reading: 'いる', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '感じ', lemma: '感じる', reading: 'かんじる', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'メンタル', lemma: 'メンタル', reading: 'めんたる', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '保っ', lemma: '保つ', reading: 'たもつ', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'た', lemma: 'た', reading: 'た', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: '。', lemma: '。', reading: '。', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
  ],
  '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。': [
    { surface: '複雑', lemma: '複雑', reading: 'ふくざつ', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'で', lemma: 'で', reading: 'で', pos: '助動詞', pos_detail: '助動詞', is_selectable: false },
    { surface: 'は', lemma: 'は', reading: 'は', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'ない', lemma: 'ない', reading: 'ない', pos: '形容詞', pos_detail: '形容詞', is_selectable: false },
    { surface: 'けれど', lemma: 'けれど', reading: 'けれど', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '着々', lemma: '着々', reading: 'ちゃくちゃく', pos: '副詞', pos_detail: '副詞', is_selectable: true },
    { surface: 'と', lemma: 'と', reading: 'と', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '取り組ん', lemma: '取り組む', reading: 'とりくむ', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'で', lemma: 'で', reading: 'で', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'いる', lemma: 'いる', reading: 'いる', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: 'この', lemma: 'この', reading: 'この', pos: '連体詞', pos_detail: '連体詞', is_selectable: false },
    { surface: 'プロジェクト', lemma: 'プロジェクト', reading: 'ぷろじぇくと', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'は', lemma: 'は', reading: 'は', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '、', lemma: '、', reading: '、', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
    { surface: '現場', lemma: '現場', reading: 'げんば', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'の', lemma: 'の', reading: 'の', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '課題解決', lemma: '課題解決', reading: 'かだいかいけつ', pos: '名詞', pos_detail: '名詞', is_selectable: true },
    { surface: 'を', lemma: 'を', reading: 'を', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: '直接', lemma: '直接', reading: 'ちょくせつ', pos: '副詞', pos_detail: '副詞', is_selectable: true },
    { surface: '目指し', lemma: '目指す', reading: 'めざす', pos: '動詞', pos_detail: '動詞', is_selectable: true },
    { surface: 'て', lemma: 'て', reading: 'て', pos: '助詞', pos_detail: '助詞', is_selectable: false },
    { surface: 'いる', lemma: 'いる', reading: 'いる', pos: '動詞', pos_detail: '動詞', is_selectable: false },
    { surface: '。', lemma: '。', reading: '。', pos: '補助記号', pos_detail: '補助記号', is_selectable: false },
  ],
};
//   '天気予報を確認して「散歩しましょう」と誘い、カフェの周りをぶらぶら歩いて過ごせて本当に良かった。',
//  '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
//    '曖昧だったコンセプトをしっかり見据えているプロジェクトは、じわじわ広がる社会現象へと発展し始めている。',
export const DEFAULT_DECKS: DeckItem[] = [
  {
    id: 'work',
    jp: '仕事',
    en: 'Work',
    color: 'var(--pine)',
    motifSvg: (
      <svg className="motif" viewBox="0 0 40 40" fill="none">
        <path d="M20 4 L24 16 L34 14 L26 22 L32 30 L22 26 L20 36 L18 26 L8 30 L14 22 L6 14 L16 16 Z" fill="#F2E9DA" opacity="0.85" />
      </svg>
    ),
  },
  {
    id: 'life',
    jp: '日常',
    en: 'Daily',
    color: 'var(--moon)',
    motifSvg: (
      <svg className="motif" viewBox="0 0 40 40" fill="none">
        <path d="M24 6 A15 15 0 1 0 24 34 A11.5 11.5 0 0 1 24 6 Z" fill="#F2E9DA" opacity="0.9" />
      </svg>
    ),
  },
  {
    id: 'leisure',
    jp: '余暇',
    en: 'Leisure',
    color: 'var(--sakura)',
    motifSvg: (
      <svg className="motif" viewBox="0 0 40 40" fill="none">
        <g fill="#F2E9DA" opacity="0.9">
          <circle cx="20" cy="10" r="6" />
          <circle cx="30" cy="17" r="6" />
          <circle cx="26" cy="29" r="6" />
          <circle cx="14" cy="29" r="6" />
          <circle cx="10" cy="17" r="6" />
        </g>
        <circle cx="20" cy="20" r="4" fill="var(--sakura)" />
      </svg>
    ),
  },
];

export const SEEDED_DEMO_CARDS: WordCard[] = [
  // --- WORK DECK ---
  {
    lemma: '見据える',
    reading: 'みすえる',
    meaning: 'to focus on; to gaze at',
    jlpt_level: 'N1',
    context_sentence: '曖昧だったコンセプトをしっかり見据えているプロジェクトは、じわじわ広がる社会現象へと発展し始めている。',
    status: 'New',
  },
  {
    lemma: '社会現象',
    reading: 'しゃかいげんしょう',
    meaning: 'social phenomenon',
    jlpt_level: 'N2',
    context_sentence: '曖昧だったコンセプトをしっかり見据えているプロジェクトは、じわじわ広がる社会現象へと発展し始めている。',
    status: 'Mastered',
  },
  {
    lemma: 'コンセプト',
    reading: 'コンセプト',
    meaning: 'concept',
    jlpt_level: 'N3',
    context_sentence: '曖昧だったコンセプトをしっかり見据えているプロジェクトは、じわじわ広がる社会現象へと発展し始めている。',
    status: 'Learning',
  },
  {
    lemma: '曖昧',
    reading: 'あいまい',
    meaning: 'vague; ambiguous; unclear',
    jlpt_level: 'N2',
    context_sentence: '曖昧だったコンセプトをしっかり見据えているプロジェクトは、じわじわ広がる社会現象へと発展し始めている。',
    status: 'New',
  },
  {
    lemma: '複雑',
    reading: 'ふくざつ',
    meaning: 'complex; complicated',
    jlpt_level: 'N3',
    context_sentence: '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
    status: 'Known',
  },
  {
    lemma: '着々',
    reading: 'ちゃくちゃく',
    meaning: 'steadily',
    jlpt_level: 'N2',
    context_sentence: '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
    status: 'New',
  },
  {
    lemma: '取り組む',
    reading: 'とりくむ',
    meaning: 'to tackle; to work on',
    jlpt_level: 'N2',
    context_sentence: '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
    status: 'New',
  },
  {
    lemma: 'プロジェクト',
    reading: 'プロジェクト',
    meaning: 'project',
    jlpt_level: 'N3',
    context_sentence: '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
    status: 'Learning',
  },
  {
    lemma: '課題解決',
    reading: 'かだいかいけつ',
    meaning: 'problem solving; issue resolution',
    jlpt_level: 'N2',
    context_sentence: '複雑ではないけれど着々と取り組んでいるこのプロジェクトは、現場の課題解決を直接目指している。',
    status: 'New',
  },

  // --- DAILY / INNER LIFE DECK ---
  {
    lemma: '草臥れる',
    reading: 'くたびれる',
    meaning: 'to get tired; to be exhausted',
    jlpt_level: 'N2',
    context_sentence: 'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
    status: 'New',
  },
  {
    lemma: '買い物する',
    reading: 'かいものする',
    meaning: 'to go shopping',
    jlpt_level: 'N5',
    context_sentence: 'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
    status: 'Mastered',
  },
  {
    lemma: 'うろうろ',
    reading: 'うろうろ',
    meaning: 'wandering aimlessly',
    jlpt_level: 'N3',
    context_sentence: 'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
    status: 'New',
  },
  {
    lemma: 'コンビニ',
    reading: 'こんびに',
    meaning: 'convenience store',
    jlpt_level: 'N4',
    context_sentence: 'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
    status: 'Known',
  },
  {
    lemma: '面倒臭い',
    reading: 'めんどうくさい',
    meaning: 'bothersome; hassle',
    jlpt_level: 'N3',
    context_sentence: 'コンビニで買い物してきた後、くたびれた様子で街をうろうろしているのは、料理を作るのが面倒くさかったからだ。',
    status: 'Learning',
  },
  {
    lemma: '思い出',
    reading: 'おもいで',
    meaning: 'memories; recollections',
    jlpt_level: 'N4',
    context_sentence: '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。',
    status: 'Learning',
  },
  {
    lemma: '切ない',
    reading: 'せつない',
    meaning: 'painful; bittersweet; heartrending',
    jlpt_level: 'N4',
    context_sentence: '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。',
    status: 'Known',
  },
  {
    lemma: 'ドキドキ',
    reading: 'どきどき',
    meaning: 'thumping; throb; excitement',
    jlpt_level: 'N3',
    context_sentence: '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。',
    status: 'Known',
  },
  {
    lemma: 'メンタル',
    reading: 'めんたる',
    meaning: 'mental state; mentality',
    jlpt_level: 'N2',
    context_sentence: '昔の思い出を振り返って泣きそうになったが、切なかった気持ちの反面、心はドキドキしているのを感じてメンタルを保った。',
    status: 'Learning',
  },

  // --- LEISURE DECK ---
  {
    lemma: '天気予報',
    reading: 'てんきよほう',
    meaning: 'weather forecast',
    jlpt_level: 'N4',
    context_sentence: '天気予報を確認して「散歩しましょう」と誘い、カフェの周りをぶらぶら歩いて過ごせて本当に良かった。',
    status: 'Known',
  },
  {
    lemma: '散歩する',
    reading: 'さんぽする',
    meaning: 'to take a walk; to stroll',
    jlpt_level: 'N5',
    context_sentence: '天気予報を確認して「散歩しましょう」と誘い、カフェの周りをぶらぶら歩いて過ごせて本当に良かった。',
    status: 'Mastered',
  },
  {
    lemma: 'カフェ',
    reading: 'カフェ',
    meaning: 'cafe; coffee shop',
    jlpt_level: 'N4',
    context_sentence: '天気予報を確認して「散歩しましょう」と誘い、カフェの周りをぶらぶら歩いて過ごせて本当に良かった。',
    status: 'Known',
  },
  {
    lemma: 'ぶらぶら',
    reading: 'ぶらぶら',
    meaning: 'aimlessly; wandering; strolling',
    jlpt_level: 'N3',
    context_sentence: '天気予報を確認して「散歩しましょう」と誘い、カフェの周りをぶらぶら歩いて過ごせて本当に良かった。',
    status: 'New',
  },
  {
    lemma: 'ハマる',
    reading: 'ハマる',
    meaning: 'to be hooked on; to be obsessed with',
    jlpt_level: 'N2',
    context_sentence: '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
    status: 'New',
  },
  {
    lemma: 'かわいい',
    reading: 'かわいい',
    meaning: 'cute; adorable',
    jlpt_level: 'N5',
    context_sentence: '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
    status: 'Mastered',
  },
  {
    lemma: '推し',
    reading: 'おし',
    meaning: 'one\'s favorite (member/character); bias',
    jlpt_level: 'N1',
    context_sentence: '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
    status: 'New',
  },
  {
    lemma: 'キラキラ',
    reading: 'キラキラ',
    meaning: 'sparkling; glittering; shining',
    jlpt_level: 'N3',
    context_sentence: '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
    status: 'New',
  },
  {
    lemma: 'アイドル',
    reading: 'アイドル',
    meaning: 'pop idol',
    jlpt_level: 'N3',
    context_sentence: '最近ハマっているアイドルは、仕草がかわいすぎるうえにキラキラ輝いていて、まさに最高の推しだ。',
    status: 'Learning',
  },
];
